{% set name = "json-schema-to-pydantic" %}
{% set version = "0.4.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/json_schema_to_pydantic-{{ version }}.tar.gz
  sha256: f71bc57c9016a6cecaf259392b4a3f35a34ad79da3934a64d21d73f526c6e28d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - uv-dynamic-versioning
    - pip
  run:
    - python >={{ python_min }}
    - pydantic >=2.10.4

test:
  imports:
    - json_schema_to_pydantic
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  summary: A Python library for automatically generating Pydantic v2 models from JSON Schema definitions
  home: https://github.com/richard-gyiko/json-schema-to-pydantic
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
